[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"

[project]
name = "pykyber"
version = "1.0.1"
description = "Kyber post-quantum key encapsulation in Rust"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "Unlicense"}
authors = [
    {name = "Yoav Haimov", email = "haimovyoav@gmail.com"}
]
keywords = ["kyber", "post-quantum", "cryptography", "pqc", "key-encapsulation"]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Rust",
    "License :: Public Domain",
    "Operating System :: OS Independent",
    "Topic :: Security :: Cryptography",
]
[project.urls]
Homepage = "https://github.com/Zikithezikit/pykyber"
Documentation = "https://github.com/Zikithezikit/pykyber/tree/v1.0.0/docs"
Repository = "https://github.com/Zikithezikit/pykyber"
Issues = "https://github.com/Zikithezikit/pykyber/issues"

[tool.maturin]
python-source = "python"
module-name = "pykyber._pykyber"
