pub const KYBER_K: usize = 3;

pub const KYBER_N: usize = 256;
pub const KYBER_Q: usize = 3329;

pub const KYBER_ETA1: usize = 2;
pub const KYBER_ETA2: usize = 2;

pub const KYBER_SYMBYTES: usize = 32;

pub const KYBER_SSBYTES: usize = 32;

pub const KYBER_POLYBYTES: usize = 384;
pub const KYBER_POLYVECBYTES: usize = KYBER_K * KYBER_POLYBYTES;

pub const KYBER_POLYCOMPRESSEDBYTES: usize = 128;
pub const KYBER_POLYVECCOMPRESSEDBYTES: usize = KYBER_K * 320;

pub const KYBER_INDCPA_PUBLICKEYBYTES: usize = KYBER_POLYVECBYTES + KYBER_SYMBYTES;
pub const KYBER_INDCPA_SECRETKEYBYTES: usize = KYBER_POLYVECBYTES;
pub const KYBER_INDCPA_BYTES: usize = KYBER_POLYVECCOMPRESSEDBYTES + KYBER_POLYCOMPRESSEDBYTES;

pub const KYBER_PUBLICKEYBYTES: usize = KYBER_INDCPA_PUBLICKEYBYTES;
pub const KYBER_SECRETKEYBYTES: usize =
    KYBER_INDCPA_SECRETKEYBYTES + KYBER_INDCPA_PUBLICKEYBYTES + 2 * KYBER_SYMBYTES;
pub const KYBER_CIPHERTEXTBYTES: usize = KYBER_INDCPA_BYTES;
